build: off

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: false

build_script:
  - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/limix/bgen/master/install.bat', 'install.bat')" && install.bat

test_script:
  - if NOT exist "%programfiles%\\bgen\\lib\\bgen.lib" exit 1
  - if NOT exist "%programfiles%\\bgen\\bin\\bgen.dll" exit 1
  - if NOT exist "%programfiles%\\bgen\\lib\\bgen_static.lib" exit 1
  - if NOT exist "%programfiles%\\bgen\\include\\bgen.h" exit 1
