os:
  - linux
  - osx
language: c
sudo: required
install:
  - bash <(curl -fsSL https://raw.githubusercontent.com/horta/zstd.install/master/install)
  - bash <(curl -fsSL https://raw.githubusercontent.com/horta/almosthere/master/install)
script:
  - bash <(curl -fsSL https://raw.githubusercontent.com/limix/bgen/master/install)
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      test -e /usr/local/include/bgen.h;
      test -e /usr/local/lib/libbgen.so;
      test -e /usr/local/lib/libbgen_static.a;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      test -e /usr/local/include/bgen.h;
      test -e /usr/local/lib/libbgen.dylib;
      test -e /usr/local/lib/libbgen_static.a;
    fi
notifications:
  email:
    recipients:
    - danilo.horta@gmail.com
    on_success: change
    on_failure: always
